[build]
  command = "npm install"
  publish = "."
  functions = "functions"

[dev]
  framework = "#custom"
  command = "node index.mjs"
  port = 3000
  targetPort = 3000
  publish = "."
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[functions]
  node_bundler = "esbuild"
